version: '3.6'

services:
  db:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: shopify
      
    image: postgres:12.9-bullseye
    ports:
      - "5478:5432"
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  api:
    build: ../Downloads/Shopify-Backend-Project-main
    depends_on:
      - db
    environment:
      STAGE: test
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://test:test@db/shopify
    ports:
      - 8000:8000
    volumes:
      - ./app:/usr/src/app/app
      - ./migrations:/usr/src/app/migrations
    restart: always

